### ISSUE TITLE
video at 30:07 regularization to use with SGD for FM 

### ISSUE THREAD

**Issue by Sandy4321** [takuti/factorization-machines#1]
He mentioned at 30:07 regularization to use with SGD for FM 
https://www.youtube.com/watch?v=LV4JLTIZxNU
Steffen Rendle, Research Scientist, Google @ MLconf SF

**Comment by Sandy4321** [comment]
data matrix usually spars, so may you clarify if you use regularization
Thanks

**Comment by takuti** [comment]
https://github.com/takuti/flurs/issues/1 takes over this topic.
